package com.api.enums;

public enum MatcherEnum {
    equals,
    notEqual,
    notNull,
    isNull,
    present,
    notPresent,
    containsString,
    datePattern,
    pattern,
    containsAll,
    equalsBoolean,
    equalsInt,
    Null,
    greaterThan,
    lessThan,
    equalTo,
    notEqualTo,
    is,
    isNot,
    arrayWithSize,
    greaterThanOrEqualTo,
    lessThanOrEqualTo,
    more,
    less,
    instanceOfBoolean,
    instanceOfString,
    instanceOfInteger,
    instanceOfArray,
    instanceOfLong,
    path,
    pathInt,
    emptyString,
    hasStringItems,
    hasIntegerItems;
}